name: GitHub Action Demo 1
env:
  prod: prod
  qual: qual
  dev: dev
on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Env ?
        options: 
          - prod
          - qual
          - dev
jobs: 
  premier-job:
    name: Premier Job
    runs-on: Ubuntu-latest
    steps: 
      - name: checkout
        if: github.ref == 'refs/main'
        run: echo "Premier job"
      - name: Step 1 prod
        if: github.event.inputs == prod
        run: echo prod
      - name: Step 2 qual
        if: github.event.inputs == qual
        run: echo qual
      - name: Step 2 dev
        if: github.event.inputs == dev
        run: echo dev
