name: GitHub Action Demo 1
env:
  prod: prod
  qual: qual
  dev: dev
on: 
  workflow_dispatch:
    inputs:
      environnement:
        type: choice
        description: Env ?
        options: 
          - prod
          - qual
          - dev
jobs: 
  premier-job:
    name: Premier Job
    runs-on: Ubuntu-latest
    steps: 
      - name: checkout
        if: github.ref != 'refs/heads/main'
        uses: actions/checkout@v4
        with:
          path: main
      - name: Current branch
        run: echo ${{github.ref}}
      - name: Step 1 prod
        if: github.event.inputs.environnement == 'prod'
        run: echo prod
      - name: Step 2 qual
        if: github.event.inputs.environnement == 'qual'
        run: echo qual
      - name: Step 3 dev
        if: github.event.inputs.environnement == 'dev'
        run: echo dev
