name: GitHub Action Demo 1
env:
  prod: prod
  qual: qual
  dev: dev
on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Env ?
        options: 
          - ${{env.prod}}
          - ${{env.qual}}
          - ${{env.dev}}
jobs: 
  premier-job:
    name: Premier Job
    runs-on: Ubuntu-latest
    steps: 
      - name: checkout
        if: github.ref == 'refs/main'
        run: echo "Premier job"
      - name: Step 1 prod
        if: github.event.inputs == ${{env.prod}}
        run: echo ${{env.prod}}
      - name: Step 2 qual
        if: github.event.inputs == ${{env.qual}}
        run: echo ${{env.qual}}
      - name: Step 2 dev
        if: github.event.inputs == ${{env.dev}}
        run: echo ${{env.dev}}
